name: 'MCReleaser'
description: 'A program to publish artifacts to multiple Minecraft-related platforms'
inputs:
  files:
    description: 'The files to upload'
    required: true
  platforms:
    description: 'The platforms to upload to'
    required: false
    default: 'all'
  mcreleaser:
    description: 'The tag of MCReleaser to be used'
    required: false
    default: master
runs:
  using: 'docker'
  image: 'ghcr.io/hsgamer/mcreleaser:${{ inputs.mcreleaser }}'
  env:
    DOCKER_FILES: ${{ inputs.files }}
    DOCKER_PLATFORMS: ${{ inputs.platforms }}
